### ISSUE TITLE
Unable to push an image to Google Container Registry using docker_registry_image with Gitlab

### ISSUE THREAD

**Issue by tiagoaragao** [kreuzwerker/terraform-provider-docker#384] opened 2022-06-09 12:50 UTC
Error: Error pushing docker image: Error response from daemon: Bad parameters and missing X-Registry-Auth: EOF
```
provider "docker" { 
  alias = "private"   
  registry_auth {
    address = "us.gcr.io" 
    username = "oauth2accesstoken"
    password = "${data.google_service_account_access_token.default.access_token}"    
  }
}
```

Version: 2.16

**Comment by suzuki-shunsuke** [comment] 2022-06-09 13:30
Duplicate of #380

**Closed** 2022-06-09 13:31 UTC
Labels: duplicate
