### ISSUE TITLE
Improved support for Docker Desktop (Mac): mounting /var/run/docker.sock leads to reconfiguration loop

### ISSUE THREAD

**Issue by alexkunin** [kreuzwerker/terraform-provider-docker#211] opened 2021-05-31 14:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is an inconvenience for Docker Desktop users (at least on Macs, did not test this on Windows, and probably it does not affect Linux): if service (pretty sure it affects container resources too, but did not check) has `/var/run/docker.sock` mounted, it is recreated every time `terraform apply` is executed.

Let me demonstrate on a smallest possible example, `main.tf`:

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.12.0"
    }
  }
}

provider "docker" {
}

resource "docker_service" "example" {
  name = "example"

  task_spec {
    container_spec {
      image = "nginx:alpine"

      mounts {
        target    = "/var/run/docker.sock"
        source    = "/var/run/docker.sock"
        type      = "bind"
        read_only = true
      }
    }
  }
}
```

Doing `init` and `apply` works fine, nothing to mention here, but if I do 2nd `apply` or `plan`(without any configuration changes), there will be pending actions, e.g. (with some irrelevant parts removed):

```
docker_service.example: Refreshing state... [id=ydsbun0wshhgmztp3auclb1ri]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # docker_service.example has been changed
  ~ resource "docker_service" "example" {
      ~ task_spec {
          ~ container_spec {
              + labels {
                  + label = "desktop.docker.io/mounts/0/Source"
                  + value = "/var/run/docker.sock"
                }
              + labels {
                  + label = "desktop.docker.io/mounts/0/SourceKind"
                  + value = "dockerSocketProxied"
                }
              + labels {
                  + label = "desktop.docker.io/mounts/0/Target"
                  + value = "/var/run/docker.sock"
                }

              + mounts {
                  + read_only = true
                  + source    = "/run/host-services/docker.proxy.sock"
                  + target    = "/var/run/docker.sock"
                  + type      = "bind"
                }
              - mounts {
                  - read_only = true -> null
                  - source    = "/var/run/docker.sock" -> null
                  - target    = "/var/run/docker.sock" -> null
                  - type      = "bind" -> null
                }
            }
        }
    }
```
And then it suggest to revert these suggested changes.

Root cause of this is the fact that Docker runs in a virtual machine, and does some additional remapping to accommodate that. Specifically, this is how output of `docker service inspect example` looks (again, only relevant parts):

```json
[
    {
        "Spec": {
            "TaskTemplate": {
                "ContainerSpec": {
                    "Labels": {
                        "desktop.docker.io/mounts/0/Source": "/var/run/docker.sock",
                        "desktop.docker.io/mounts/0/SourceKind": "dockerSocketProxied",
                        "desktop.docker.io/mounts/0/Target": "/var/run/docker.sock"
                    },
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/run/host-services/docker.proxy.sock",
                            "Target": "/var/run/docker.sock",
                            "ReadOnly": true
                        }
                    ],
                },
            },
        },
    }
]
```

BTW, this behavior is not specific to `terraform-provider-docker`, as the following command yields same `inspect` output:

```bash
docker service create --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --name example nginx:alpine
```

This is a major inconvenience in a limited set of situations (need mounting Docker control socket, need to run this in Docker Desktop for Mac). I don't expect this to be ever implemented, but felt like it's worth reporting. Maybe also worth pinging Docker Desktop team, they could have some solution?

Some additional info. Funny enough, running an image from command line (not a service) does not add these mappings, and `docker inspect` output looks like this:

```bash
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name example nginx:alpine
docker inspect example2
```
```json
[
    {
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
    }
]
```

**Comment by mavogel** [comment] 2021-05-31 20:05
Hi @alexkunin thanks for reporting this. Interesting behavior TBH. 

>  I don't expect this to be ever implemented, but felt like it's worth reporting. Maybe also worth pinging Docker Desktop team, they could have some solution?

Sounds good to me. Feel free to link this issue then. IMHO `dind` is something nobody did with this provider until now. If I get you right, we can close this because it's not a bug, but more a report from your side?

**Comment by alexkunin** [comment] 2021-06-01 05:37
Yes, just a report, for future references etc.

**Comment by mavogel** [comment] 2021-06-01 05:59
Alright, will close it for now.

**Closed by mavogel** 2021-06-01 05:59 UTC
Labels: report

**Comment by davidvasandani** [comment] 2022-02-17 07:15
@alexkunin any chance did you find a workaround for this?

**Comment by alexkunin** [comment] 2022-02-17 07:47
@davidvasandani too bad, no workaround so far.
