### ISSUE TITLE
Not defining "working_dir" triggers container replacement on every run

### ISSUE THREAD

**Issue by quentinadam** [kreuzwerker/terraform-provider-docker#14] opened 2020-12-02 13:29 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/digitalocean/digitalocean v2.2.0
+ provider registry.terraform.io/kreuzwerker/docker v2.8.0
```

### Affected Resource(s)
docker_container

### Terraform Configuration Files
```hcl
data "docker_registry_image" "container" {
  name = "${var.registry_address}/xxxxxxx/container"
}

resource "docker_image" "container" {
  name          = "${data.docker_registry_image.container.name}@${data.docker_registry_image.container.sha256_digest}"
  keep_locally  = true
  pull_triggers = [data.docker_registry_image.container.sha256_digest]
}

resource "docker_container" "container" {
  name        = "container"
  image       = docker_image.container.latest
}
```

### Debug Output
```
docker_container.container must be replaced
-/+ resource "docker_container" "container" {
        attach            = false
      + bridge            = (known after apply)
      ~ command           = [
          - "npm",
          - "run",
          - "--prefix",
          - "./packages/container/backend",
          - "start",
        ] -> (known after apply)
      + container_logs    = (known after apply)
      - cpu_shares        = 0 -> null
      - dns               = [] -> null
      - dns_opts          = [] -> null
      - dns_search        = [] -> null
      ~ entrypoint        = [
          - "docker-entrypoint.sh",
        ] -> (known after apply)
      ~ env               = [] -> (known after apply)
      + exit_code         = (known after apply)
      ~ gateway           = "172.18.0.1" -> (known after apply)
      - group_add         = [] -> null
      ~ hostname          = "81d8ace62633" -> (known after apply)
      ~ id                = "81d8ace62633e78d620321b7168d46059af6011864b34958eab2614c3d89e0c5" -> (known after apply)
        image             = "sha256:b7653b3e02763582647ea37bc6220db767478e8b484a47702114d8d8c256b560"
      ~ ip_address        = "172.18.0.3" -> (known after apply)
      ~ ip_prefix_length  = 16 -> (known after apply)
      ~ ipc_mode          = "private" -> (known after apply)
      - links             = [] -> null
        log_driver        = "json-file"
        log_opts          = {
            "max-file" = "10"
            "max-size" = "100m"
        }
        logs              = false
      - max_retry_count   = 0 -> null
      - memory            = 0 -> null
      - memory_swap       = 0 -> null
        must_run          = true
        name              = "container"
      ~ network_data      = [
          - {
              - gateway                   = "172.18.0.1"
              - global_ipv6_address       = ""
              - global_ipv6_prefix_length = 0
              - ip_address                = "172.18.0.3"
              - ip_prefix_length          = 16
              - ipv6_gateway              = ""
              - network_name              = "network"
            },
        ] -> (known after apply)
      - network_mode      = "default" -> null
      - privileged        = false -> null
      - publish_all_ports = false -> null
        read_only         = false
        remove_volumes    = true
        restart           = "no"
        rm                = false
      ~ shm_size          = 64 -> (known after apply)
        start             = true
      - sysctls           = {} -> null
      - tmpfs             = {} -> null
      - working_dir       = "/workdir" -> null # forces replacement
   }
```

### Expected Behavior
The fact that I am not defining "working_dir" in "docker_container" should not always trigger a forced replacement.

### Actual Behavior
Every time I run `terraform apply` the container gets replaced because I did not define "working_dir" in "docker_container"

**Comment by suzuki-shunsuke** [comment] 2020-12-02 14:04
Hmm..
I fixed the bug by https://github.com/hashicorp/terraform-provider-docker/pull/272 ...

**Comment by suzuki-shunsuke** [comment] 2020-12-02 14:07
Oh, `Computed: true` was removed??
https://github.com/kreuzwerker/terraform-provider-docker/blob/8476f9b21a41a07bf077d66ea4b59cf00b409f5c/docker/resource_docker_container.go#L197-L208

**Comment by suzuki-shunsuke** [comment] 2020-12-02 14:15
`Computed: true` was removed by this commit.
https://github.com/hashicorp/terraform-provider-docker/commit/cdc0d912cc7f44400e587a997594e83688dc0430#

**Comment by suzuki-shunsuke** [comment] 2020-12-02 14:31
Will be fixed by #15

**Comment by dubo-dubon-duponey** [comment] 2020-12-02 19:18
@suzuki-shunsuke that might be fixed already:

https://github.com/hashicorp/terraform-provider-docker/issues/319

https://github.com/hashicorp/terraform-provider-docker/pull/320

@quentinadam do you mind trying with master?

**Comment by quentinadam** [comment] 2020-12-02 19:25
Happy to try that of course. I guess I should change something in the "versions.tf" file to use the latest master version instead of version 2.8.0 ? Would you pointing out what I should change in that file ? Here is the current version of the versions.tf file :

```
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
    }
    docker = {
      source = "kreuzwerker/docker"
    }
  }
  required_version = ">= 0.13"
}
```

**Comment by dubo-dubon-duponey** [comment] 2020-12-02 20:56
@quentinadam 

https://github.com/kreuzwerker/terraform-provider-docker/#developing-the-provider

These instructions suggest that you can just build it and use it by removing the version.

I don't remember if this ^ works or not though.

Here is what I've been doing (possibly because the above ^ is outdated?)

1. clone and build (`make build`) - you should now have a built plugin in your GOPATH/bin folder.

In my case:

```
dmp@macArena:~/Projects/Deploy/home$ which terraform-provider-docker
/Users/dmp/Applications/bin/gvm/pkgsets/go1.15/global/bin/terraform-provider-docker
```

2. Create `~/.terraformrc` with the following:

```
provider_installation {
  filesystem_mirror {
    path    = "/Users/dmp/Projects/Deploy/home/built-plugins/"
    include = ["terraform-providers/docker"]
  }
}
```
^ adapt this path to whatever suits you.

3. Copy the plugin 

```
dest=/Users/dmp/Projects/Deploy/home/built-plugins/registry.terraform.io/terraform-providers/docker/2.7.2/darwin_amd64
mkdir -p "$dest"

cp $(which terraform-provider-docker) "$dest"
```

Be sure to adapt the version and platform in the path to match your mileage.

Curious if there is a simpler / more straightforward way to achieve that.

**Comment by suzuki-shunsuke** [comment] 2020-12-02 22:29
https://github.com/kreuzwerker/terraform-provider-docker/issues/14#issuecomment-737441037

Oh, sorry. I confirmed that this is fixed at the master.
I'll close #15 .

**Comment by mavogel** [comment] 2020-12-03 17:39
Then we'd trigger a release as soon as #12 is fixed

**Comment by dubo-dubon-duponey** [comment] 2020-12-03 18:14
@mavogel @suzuki-shunsuke I've been thinking more about this patch.

It makes the situation better, for sure, but I now think it's wrong / incomplete.

Here is what *should* happen:

 * if working_dir is explicitly set to value A:
    * if the existing container has value B (!= A) for working_dir, rebuild
    * if the existing container has value A, do not rebuild
 * if working_dir is not set, or set to "":
    * if working_dir was previously NOT set (or set to to ""), do NOT rebuild (regardless of the value of working_dir in the running container)
    * if working_dir was previously set to value B (!= ""), and if the container "in dockerfile" working_dir was C (!= B), then rebuild

I have no idea how to do that... since this involve looking up both the past value of working_dir, and the value of working_dir if the container was started without explicitly overriding working_dir...

With what we have right now, this will be wrong in the following scenario:

 * container was previously started with working_dir = A (where A is different from whatever the container had internally)
 * we now ask for a reapply with working_dir = ""
 * -> the container will not be rebuilt (while it should)

Again, I think what we have now is much better than before, but it will still be wrong in corner cases like that...

**Comment by suzuki-shunsuke** [comment] 2020-12-16 02:39
@mavogel How about releasing the new version? #26 was merged.

**Comment by mavogel** [comment] 2020-12-25 08:13
done @suzuki-shunsuke ->  https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.9.0

**Comment by quentinadam** [comment] 2020-12-25 14:12
Great ! I am confirming that it now works as expected (not defining "working_dir" does not trigger a container replacement on every run).

**Comment by mavogel** [comment] 2020-12-25 14:49
Happy to hear that! Will close it.

**Closed by mavogel** 2020-12-25 14:49 UTC
Labels: bug, r/container
