### ISSUE TITLE
there are no examples for the usage or syntax of these nested features - no clarity on if an equals sign or quotation marks are supposed to be used

### ISSUE THREAD

**Issue by owenwu811** [kreuzwerker/terraform-provider-docker#514] opened 2023-02-12 01:11 UTC
[Nested Schema for ports](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#nested-schema-for-ports)
Required:

[internal](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#internal) (Number) Port within the container.
Optional:

[external](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#external) (Number) Port exposed out of the container. If not given a free random port >= 32768 will be used.
[ip](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#ip) (String) IP address/mask that can access this port. Defaults to 0.0.0.0.
[protocol](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#protocol) (String) Protocol that can be used over this port. Defaults to tcp.

**Comment by Junkern** [comment] 2023-02-17 14:35
If you scroll down on the page you linked, you would see an example: https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#example 

In general, a nested schema is always
```
attribute_name {
}
```

If you see something like 
```
attribute_name = {
}
```

than this is a simple attribute of a `map` type.

https://developer.hashicorp.com/terraform/language/syntax/configuration

Closing because not a bug

**Closed by Junkern** 2023-02-17 14:35 UTC
