### ISSUE TITLE
Stale plan issue is raised when terraform plan is created with using -var-files parameter.

### ISSUE THREAD

**Issue by gkarabut** [kreuzwerker/terraform-provider-docker#444] opened 2022-08-31 15:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version
0.15.5
2.20.2

### Expected Behaviour

Docker image gets built with no issues
### Actual Behaviour

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for docker_registry_image.data_preparation to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker"
│ produced an invalid new value for .build[0].context: was cty.StringVal(".:2d7f15b77ed3a2dbed33da74a1d4aad0009cc6c3e349a58cd350974aa32be04c"), but now
│ cty.StringVal(".:e7caf789fab71ea05aaf6a1773884236b19afe4f82b090ba9a670ba3ee41c57c").
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
│ Error: Provider produced inconsistent final plan
│ When expanding the plan for docker_registry_image.data_preparation to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker"
│ produced an invalid new value for .build[0].context: was cty.StringVal(".:2d7f15b77ed3a2dbed33da74a1d4aad0009cc6c3e349a58cd350974aa32be04c"), but now
│ cty.StringVal(".:e7caf789fab71ea05aaf6a1773884236b19afe4f82b090ba9a670ba3ee41c57c").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce
main file:
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "2.20.2"
    }
  }
}

provider "aws"{
    region = var.region
}

provider "docker" {
  registry_auth {
    address  = local.aws_ecr_url
    username = data.aws_ecr_authorization_token.ecr_token.user_name
    password = data.aws_ecr_authorization_token.ecr_token.password
  }
}

locals {
   tags = {
    created_by = "terraform"
   }
   country = var.country_name
   repository_name = "sagemaker-nbx-us-brz"
   aws_ecr_url = "12345.dkr.ecr.us-east-1.amazonaws.com"
}

data "aws_ecr_authorization_token" "ecr_token" {}

resource "docker_registry_image" "data_preparation" {
    name = "${local.aws_ecr_url}/${local.repository_name}:sometag"
    build {
      context = "${path.root}"
      dockerfile = "${path.root}/../Dockerfile"
      no_cache = true
    }
}

variables.tf
variable "region" {
    type = string
}
variable "country_name"{
   type = string
}

dev.tfvars:
#infrastructure
region = "ap-southeast-1"
country_name = "australia"

Dockerfile:
FROM ubuntu
CMD echo hello
ENV SPARK_VERSION=3.1.2

When using -var parameters for terraform apply it get's executed with no issues:
terraform apply -var "region=ap-southeast-1"  -var "country_name=australia"

However using -var-file for building plan and applying it afterwards leads to error:
terraform plan -var-file=dev.tfvars -out=plan
terraform apply plan

Please advice how to pass to provider variables in a file

**Comment by Junkern** [comment] 2022-09-01 07:24
Thanks for reporting! This is an duplicate of https://github.com/kreuzwerker/terraform-provider-docker/issues/290 and https://github.com/kreuzwerker/terraform-provider-docker/issues/385

The issue is nothing to do with the passing of variables but with a bug in the `docker_registry_image`. Fixing this bug is a breaking change and requires a new major version (we sadly don't have an ETA for that, yet)

**Closed by Junkern** 2022-09-01 07:24 UTC
