### ISSUE TITLE
Forces Replacement because of diffrent Images (SHA256 -> Normal Image Name)

### ISSUE THREAD

**Issue by SaveFeelix** [kreuzwerker/terraform-provider-docker#522] opened 2023-03-09 13:15 UTC
### Community Note

* Please vote on this issue by adding a
  👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original
  issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help
  prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```bash
$ terraform --version
Terraform v1.4.0
on linux_amd64
```

### Affected Resource(s)

* `docker_container`

### Terraform Configuration Files

1. `main.tf`

```hcl
terraform {
  # Unimportent for the Issue!
  #backend "http" {
  #  lock_method    = "POST"
  #  unlock_method  = "DELETE"
  #  retry_wait_max = 5
  #}


  required_providers {
    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

provider "docker" {
  # Unimportent for the Issue!
  #host     = "ssh://${var.SSH_USERNAME}@${var.SSH_HOSTNAME}"
  #ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
  #registry_auth {
  # address  = var.DOCKER_REGISTRY
  # password = var.DOCKER_PASSWORD
  # username = var.DOCKER_USERNAME
}
```

2. `images.tf`

```hcl
resource "docker_image" "redis-image" {
  name = "redis:${var.REDIS_VERSION}"
}
resource "docker_image" "database-image" {
  name = "postgres:${var.DATABASE_VERSION}"
}
resource "docker_image" "web-image" {
  name = "nginx:${var.WEB_VERSION}"
}
```

3. `container.tf`

```hcl
resource "docker_container" "redis-container" {
  depends_on = [
    docker_image.redis-image,
    docker_network.redis-server-network
  ]
  image    = docker_image.redis-image.name
  name     = "${var.CONTAINER_PREFIX}Redis"
  hostname = "redis"
  restart  = "always"
  networks_advanced {
    name = docker_network.redis-server-network.name
  }
}

resource "docker_container" "database-container" {
  depends_on = [
    docker_image.database-image,
    docker_network.database-server-network,
    docker_volume.database-volume
  ]
  image    = docker_image.database-image.name
  name     = "${var.CONTAINER_PREFIX}Database"
  hostname = "database"
  restart  = "always"
  env      = [
    "POSTGRES_PASSWORD=${var.POSTGRES_PASSWORD}"
  ]
  networks_advanced {
    name = docker_network.database-server-network.name
  }
  volumes {
    volume_name    = docker_volume.database-volume.name
    container_path = "/var/lib/postgresql/data"
  }
}

resource "docker_container" "rest-api-container" {
  depends_on = [
    docker_image.web-image,
    docker_network.redis-server-network,
    docker_network.database-server-network,
    docker_container.database-container,
    docker_container.redis-container
  ]
  image   = docker_image.web-image.name
  name    = "${var.CONTAINER_PREFIX}REST-API"
  restart = "always"
  networks_advanced {
    name = docker_network.database-server-network.name
  }
  networks_advanced {
    name = docker_network.redis-server-network.name
  }
}
```

### Debug Output

This is the Debug output of the Terraform-Plan:

https://pastebin.com/HResnZ0G

This is the normal output of the Terraform-Plan:

https://pastebin.com/zUtrZKTp

### Expected Behaviour

```
Terraform will perform the following actions:
# docker_container.database-container must be replaced
-/+ resource "docker_container" "database-container" {
[...] // Some Changes
~ image = "postgres:15.2-alpine" -> "postgres:15.2-alpine" # forces replacement
[...] // Some Changes
}

# docker_container.redis-container must be replaced
-/+ resource "docker_container" "redis-container" {
[...] // Some Changes
~ image = "redis:7.0.9-alpine" -> "redis:7.0.9-alpine"
[...] // Some Changes
}

# docker_container.rest-api-container must be replaced
-/+ resource "docker_container" "rest-api-container" {
[...]// Some Changes
~ image = "nginx:1.23.3-alpine-slim" -> "nginx:1.23.3-alpine-slim" # forces replacement
[...]// Some Changes
}

Plan : 3 to add, 0 to change, 3 to destroy.([or] Plan : 0 to add, 3 to change, 0 to destroy)
```

### Actual Behaviour

```
Terraform will perform the following actions:
# docker_container.database-container must be replaced
-/+ resource "docker_container" "database-container" {
[...] // No changes
~ image = "sha256:6a35e2c987a69cd37f078e911ea336e0576d980fa5c3eceac3e24e3b3e90eeb1" -> "postgres:15.2-alpine" # forces replacement
[...] // No changes
}

# docker_container.redis-container must be replaced
-/+ resource "docker_container" "redis-container" {
[...] // No changes
~ image = "sha256:5130e5ba7d244aa17bf8ad36f7a1ef08dff389090b42a25a3b6b6bcd22c4fb52" -> "redis:7.0.9-alpine" # forces replacement
[...] // No changes
}
# docker_container.rest-api-container must be replaced

-/+ resource "docker_container" "rest-api-container" {
[...] // No changes
~ image = "sha256:c590972254923ed7847ab22756bdd8d6a3529a099cb1ea59663daabfa3fd940b" -> "nginx:1.23.3-alpine-slim" # forces replacement
[...] // No changes
}
Plan : 3 to add, 0 to change, 3 to destroy.
```

### Steps to Reproduce

1. `terraform init` // Comment out the SSH-Configuration in `main.tf`. The same output will appear on Windows with
   Docker-Desktop
2. `%define variables% terraform plan -out planfile`

### Important Factoids

The containers should run on my private Docker-Server. Connection is defined in `main.tf`.

The Terraform-State is stored on GitLab.

**Comment by Junkern** [comment] 2023-03-15 12:44
This is a duplicate of #426, will close and track the progress in the already existing ticket

**Closed by Junkern** 2023-03-15 12:44 UTC
Labels: r/container
