### ISSUE TITLE
Can't pull image from private AWS ECR repository (401 Unauthorized)

### ISSUE THREAD

**Issue by 5er9e1** [kreuzwerker/terraform-provider-docker#460] opened 2022-09-19 06:42 UTC
How to reproduce:

## Step 1. Create first terraform environment to create parent image and push it into ECR:

```terraform
provider "aws" {
  region = "ap-northeast-1"
}

data "aws_ecr_authorization_token" "token" {}
data "aws_caller_identity" "aws_account_info" {}

provider "docker" {
  registry_auth {
    address  = "${data.aws_caller_identity.aws_account_info.account_id}.dkr.ecr.ap-northeast-1.amazonaws.com"
    username = data.aws_ecr_authorization_token.token.user_name
    password = data.aws_ecr_authorization_token.token.password
  }
}

resource "aws_ecr_repository" "parent" {
  name                 = "parent-test-image"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = false
  }
}

resource "docker_registry_image" "parent" {

  depends_on = [
    aws_ecr_repository.parent
  ]

  name = "${data.aws_caller_identity.aws_account_info.account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/parent-test-image:latest"

  build {
    context      = "${path.cwd}"
    dockerfile   = "Dockerfile"
    force_remove = true
    no_cache     = true
    build_id     = "x"
  }
}

terraform {
  required_version = "~> 1.2"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2"
    }
  }

  backend "local" {
    path = "state.tfstate"
  }
}
```

where `Dockerfile` is:

```Dockerfile
FROM alpine:latest
RUN echo "some changes" > /tmp/some_changes.txt
```

## Step 2. Remove local `parent` to force pull remote image

```
docker rmi -f `{{ID OF CREATED PARENT IMAGE}}`
```

## Step 3. Create second terraform environment to be able pull parent image and create child images and push it to ECR:

```terraform
provider "aws" {
  region = "ap-northeast-1"
}

data "aws_ecr_authorization_token" "token" {}
data "aws_caller_identity" "aws_account_info" {}

provider "docker" {
  registry_auth {
    address  = "${data.aws_caller_identity.aws_account_info.account_id}.dkr.ecr.ap-northeast-1.amazonaws.com"
    username = data.aws_ecr_authorization_token.token.user_name
    password = data.aws_ecr_authorization_token.token.password
  }
}

resource "aws_ecr_repository" "child" {
  name                 = "child-test-image"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = false
  }
}

resource "docker_registry_image" "child" {

  depends_on = [
    aws_ecr_repository.child
  ]

  name = "${data.aws_caller_identity.aws_account_info.account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/child-test-image:latest"

  build {
    context      = "${path.cwd}"
    dockerfile   = "Dockerfile"
    force_remove = true
    no_cache     = true
    build_id     = "x"
  }
}

terraform {
  required_version = "~> 1.2"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2"
    }
  }

  backend "local" {
    path = "state.tfstate"
  }
}
```

where `Dockerfile` is:

```Dockerfile
FROM {{AWS ACCOUNT ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/parent-test-image:latest
RUN echo "some changes 2" > /tmp/some_changes2.txt
```

## Step 4. Smile and getting error:

```test
Error: Error building docker image: 0: failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 401 Unauthorize

│   with docker_registry_image.child,
│   on main.tf line 25, in resource "docker_registry_image" "child":
│   25: resource "docker_registry_image" "child" {
```

## Step 5. After a short cry trying to pull parent image manually:

```text
aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin {{AWS ACCOUNT ID}}.dkr.ecr.ap-northeast-1.amazonaws.com
Login Succeeded
docker pull  {{AWS ACCOUNT ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/parent-test-image:latest
```

## Conclusion is:
docker provider don't use logged-in docker credentials even if login to docker manually (`aws ecr get-login-password --region ap-northeast-1 | docker login ...`) when puling image. But using credentials when pushing image.

Should this behavior considered as bug?

**Comment by Junkern** [comment] 2022-09-21 14:49
Short: This is expected behaviour.

Longer explanation:
#### After Step 1
You have pushed `parent-test-image:latest` to ECR and also have it locally
#### After Step 2
You deleted `parent-test-image:latest` locally, it now only exists in ECR

#### Step 3
You tell docker "hey, here is a dockerfile, build it and please use `parent-test-image:latest` image".
But you did delete the local image. The `docker_registry_image` is only for representing an image in an registry. It does not take a look at the `FROM` directive and pull the image.

You need to use the [`docker_image`](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/image) resource in order to pull the image from ECR to local

In Step 5 you are exactly doing what the `docker_image` resource is doing.

I hope this makes sense.
Closing because it works as expected.

**Closed by Junkern** 2022-09-21 14:49 UTC

**Comment by 5er9e1** [comment] 2022-09-22 03:29
@Junkern 

> Short: This is expected behaviour.

Do you every time running `docker pull` manually before `docker build` command? Or maybe you manually pulling it when using `docker-compose`? I guess not. At least I don't, because docker pulling non-existant images automatically.

> It does not take a look at the FROM directive and pull the image.

But docker does. It is so non-intuitive that Docker sometimes using credentials and sometimes don't. Credentials provided for whole `provider`. Why `docker_image` is using it but `docker_registry_image` don't. At least if here will be error like `no local image found` it is okay, but it is hard to understand that thing trying to pull image is `Docker` by himself but not `docker_registry_image` object. Where starting docker and ending `docker_registry_image`?

Anyway thanks for the solution. I hope `docker_image` will help me

**Comment by 5er9e1** [comment] 2022-09-22 08:00
@Junkern 
By the way `docker_container` pulling image (and using credentials) automatically even if it doesn't exists locally.
So looks like only `docker_registry_image` behavior is different

**Comment by OJFord** [comment] 2024-08-29 15:00
This fails even if the name is the complete ECR URL

**Comment by akinmetin** [comment] 2024-12-29 19:22
Today I had the same issue and spent my entire day to debug this error message even if I enabled terraform debug logs.
I was actually expecting the module to pull the image automatically if the authentication credentials are already provided under `registry_auth` in the provider part.
Is it possible to add more logs about this error to be more specific for the other people or introduce the feature to pull the image automatically from the private ECR in case of it's not available locally and credentials are provided?
@Junkern
